GAME_NAME = "Grand Theft Auto V"
GTA5 = "GTA5.exe"
BE="GTA5_BE.exe"
LAUNCHER = "Launcher.exe"
PLAY_GTA5 = "PlayGTAV.exe"
ROCKSTAR_SERVICE = "RockstarService.exe"
ERROR_HANDLER = "RockstarErrorHandler.exe"
SC_HELPER = "SocialClubHelper.exe"